# Generated by Django 5.1.4 on 2024-12-25 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999, message='Phone number cannot exceed 10 digits.')]),
        ),
    ]
